"""
contracts/interfaces.py
========================
Structural (Protocol) contracts for every pluggable component in the voice agent.

Defines ``typing.Protocol`` classes (PEP 544 structural subtyping) for each
major subsystem:

  - ``STTEngine``           : Speech-to-Text adapter (e.g. Deepgram)
  - ``TTSEngine``           : Text-to-Speech adapter (e.g. Deepgram Aura, ElevenLabs)
  - ``KnowledgeBaseEngine`` : RAG / knowledge retrieval (e.g. PGVector)
  - ``LLMEngine``           : Large Language Model adapter (e.g. Gemini, Groq)
  - ``CRMEngine``           : CRM integration (e.g. LeadSquared)
  - ``PolicyEngine``        : Safety & compliance filter

Why ``Protocol`` rather than abstract base classes:
  1. Structural typing — any class that implements the required methods is
     considered conformant; no explicit inheritance needed. Swapping vendors
     (e.g. Deepgram → AssemblyAI) only requires implementing the methods.
  2. Static analysis — mypy / Pyright verify concrete implementations satisfy
     the contract at check time.
  3. Decoupled imports — the orchestrator imports only these Protocol
     definitions, never the concrete adapter classes.

Method signatures are taken verbatim from the company project to keep future
ports drop-in compatible.
"""

from typing import AsyncGenerator, Protocol, List, Any, Optional, Dict
from .schemas import (
    TranscriptSegment,  # noqa: F401  — re-exported for convenience
    LLMRequest,         # noqa: F401
    LLMResponse,        # noqa: F401
    CallContext,
    EscalationEvent,
)


class STTEngine(Protocol):
    """
    Contract for a Speech-To-Text adapter.

    Supported implementations: Deepgram, AssemblyAI, Vosk.

    Typical lifecycle::

        engine = DeepgramSTTEngine(...)
        await engine.connect()            # Open WebSocket to STT provider
        await engine.send_audio(chunk)    # Stream audio bytes
        await engine.close()              # Close the WebSocket
    """

    async def connect(self) -> bool:
        """Open the connection to the STT provider. Returns True on success."""
        ...

    async def send_audio(self, audio_chunk: bytes) -> None:
        """Forward a raw audio chunk (e.g. Mu-Law PCMU bytes) for transcription."""
        ...

    async def close(self) -> None:
        """
        Gracefully close the STT connection. Should flush any buffered audio
        and wait for the final transcript before closing the WebSocket.
        """
        ...


class TTSEngine(Protocol):
    """
    Contract for a Text-To-Speech adapter.

    Supported implementations: Deepgram Aura, ElevenLabs, OpenAI TTS.

    ``speak`` is an async generator so audio can be streamed to Twilio
    chunk-by-chunk as it arrives, minimising time-to-first-audio.
    """

    async def speak(
        self,
        text: str,
        call_id: Optional[str] = None,
    ) -> AsyncGenerator[bytes, None]:
        """Yield raw audio bytes as they arrive from the TTS provider."""
        ...

    def stop_current_speech(self, call_id: str) -> str:
        """Interrupt the current TTS playback for the given call."""
        ...

    async def close(self) -> None:
        """Release any resources held by the TTS engine."""
        ...


class KnowledgeBaseEngine(Protocol):
    """
    Contract for a RAG knowledge-retrieval adapter.

    Supported implementations: PGVector + PostgreSQL.

    ``search`` is synchronous in the current PGVector implementation. An async
    variant can be added as a second method without breaking existing callers.
    """

    def search(self, query: str, top_k: int = 2) -> tuple[str, float]:
        """
        Retrieve the most relevant knowledge-base chunks for a query.

        Returns
        -------
        tuple[str, float]
            (concatenated chunk text, best confidence score).
        """
        ...


class LLMEngine(Protocol):
    """
    Contract for a Large Language Model adapter.

    Supported implementations: Gemini, OpenAI GPT-4, Anthropic Claude, Groq.

    Two generation modes:
      - ``generate_stream``  — yields text tokens as they arrive (main loop)
      - ``generate_response`` — waits for full text (used for summarisation)
    """

    def start_new_session(self) -> List[Any]:
        """Initialise a new chat history list for a call session."""
        ...

    async def generate_stream(
        self,
        text: str,
        history: List[Any],
        caller_number: Optional[str] = None,
    ) -> AsyncGenerator[str, None]:
        """Yield text tokens as they are generated by the LLM."""
        ...

    async def generate_response(
        self,
        text: str,
        history: Optional[List[Any]],
    ) -> str:
        """Return the full generated text (non-streaming)."""
        ...


class CRMEngine(Protocol):
    """
    Contract for a Customer Relationship Management integration.

    Supported implementations: LeadSquared, Salesforce, HubSpot.

    All methods are async because CRM APIs involve network I/O and must not
    block the voice agent's asyncio event loop.
    """

    async def create_ticket(
        self,
        transcript: str,
        summary: str,
        sentiment: str,
        structured_turns: Optional[List[Dict[str, Any]]] = None,
        **kwargs: Any,
    ) -> Any:
        """Create a new support ticket in the CRM for a completed call."""
        ...

    async def log_call(
        self,
        call_id: str,
        caller_phone: str,
        caller_type: str = "unknown",
        summary: str = "",
        transcript: str = "",
        sentiment: str = "neutral",
        duration_seconds: int = 0,
    ) -> Any:
        """Log a completed call in the CRM's call-history / activity feed."""
        ...

    async def create_callback(
        self,
        ticket_id: str,
        phone_number: str,
        reason: str,
        preferred_time: str = "ASAP",
    ) -> Any:
        """Schedule a callback for a caller who requested human follow-up."""
        ...

    async def get_ticket_status(self, ticket_id: str) -> dict:
        """Retrieve the current status of a CRM ticket."""
        ...

    async def get_ticket_by_phone(self, phone_number: str) -> dict:
        """Look up a CRM ticket by the caller's phone number."""
        ...


class PolicyEngine(Protocol):
    """
    Contract for the safety and compliance filter.

    Sits between the LLM output and the TTS engine, validating responses
    before they are spoken. Also classifies inbound user text for escalation
    triggers.
    """

    def validate_response(self, context: CallContext, response_text: str) -> bool:
        """
        Validate an LLM-generated response before it is spoken aloud.

        Returns True if safe; False if it must be replaced with a
        policy-compliant fallback.
        """
        ...

    def check_escalation(self, user_text: str) -> EscalationEvent:
        """
        Determine whether the user's text warrants human escalation.

        Returns an ``EscalationEvent`` if escalation is required.
        """
        ...
